## Deliverable 2. Create a Customer Travel Destinations Map.

In [14]:
# Dependencies and Setup
import pandas as pd
import numpy as np
import requests
import gmaps
import sys
import os
sys.path.insert(1, os.path.join("..","."))
# Import API key
from config import g_key

# Configure gmaps API key
gmaps.configure(api_key=g_key)

In [2]:
# 1. Import the WeatherPy_Database.csv file. 
city_data_df = pd.read_csv("../Weather_Database/WeatherPy_Database.csv")
city_data_df.head()

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,0,Albany,US,42.6001,-73.9662,59.34,34,100,1.01,overcast clouds
1,1,Yuancheng,CN,36.6520,107.7896,57.58,71,100,4.32,overcast clouds
2,2,High Level,CA,58.5169,-117.1360,37.51,93,100,13.80,light rain
3,3,Rikitea,PF,-23.1203,-134.9692,77.29,83,63,13.22,light rain
4,4,Mataura,NZ,-46.1927,168.8643,57.47,99,100,2.62,light rain

In [3]:
# 2. Prompt the user to enter minimum and maximum temperature criteria 
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 75
What is the maximum temperature you would like for your trip? 90

In [4]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)].dropna()
preferred_cities_df.head(10)

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
3,3,Rikitea,PF,-23.1203,-134.9692,77.29,83,63,13.22,light rain
9,9,Georgetown,MY,5.4112,100.3354,84.13,93,20,8.05,few clouds
28,28,Jensen Beach,US,27.2545,-80.2298,85.06,64,40,10.36,scattered clouds
29,29,Romita,MX,20.8667,-101.5167,89.42,10,2,8.57,clear sky
37,37,Manaure,CO,11.7751,-72.4445,85.69,62,100,15.99,overcast clouds
38,38,Hilo,US,19.7297,-155.0900,89.28,77,100,6.91,overcast clouds
44,44,Butaritari,KI,3.0707,172.7902,81.50,79,100,15.82,light rain
47,47,Avarua,CK,-21.2078,-159.7750,82.45,78,40,8.05,scattered clouds
49,49,Hithadhoo,MV,-0.6000,73.0833,83.61,77,12,15.84,few clouds
54,54,Taoudenni,ML,22.6783,-3.9836,89.76,10,0,10.65,clear sky

In [5]:
# 4a. Determine if there are any empty rows.
preferred_cities_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 218 entries, 3 to 706
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   City_ID              218 non-null    int64
 1   City                 218 non-null    object
 2   Country              218 non-null    object
 3   Lat                  218 non-null    float64
 4   Lng                  218 non-null    float64
 5   Max Temp             218 non-null    float64
 6   Humidity             218 non-null    int64
 7   Cloudiness           218 non-null    int64
 8   Wind Speed           218 non-null    float64
 9   Current Description  218 non-null    object
dtypes: float64(4), int64(3), object(3)
memory usage: 18.7+ KB

In [6]:
# 4b. Drop any empty rows and create a new DataFrame that doesn’t have empty rows.
clean_df = preferred_cities_df.dropna()
clean_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 218 entries, 3 to 706
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   City_ID              218 non-null    int64
 1   City                 218 non-null    object
 2   Country              218 non-null    object
 3   Lat                  218 non-null    float64
 4   Lng                  218 non-null    float64
 5   Max Temp             218 non-null    float64
 6   Humidity             218 non-null    int64
 7   Cloudiness           218 non-null    int64
 8   Wind Speed           218 non-null    float64
 9   Current Description  218 non-null    object
dtypes: float64(4), int64(3), object(3)
memory usage: 18.7+ KB

In [7]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = clean_df[["City", "Country", "Max Temp", "Current Description", "Lat", "Lng"]].copy()

# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
3,Rikitea,PF,77.29,light rain,-23.1203,-134.9692,
9,Georgetown,MY,84.13,few clouds,5.4112,100.3354,
28,Jensen Beach,US,85.06,scattered clouds,27.2545,-80.2298,
29,Romita,MX,89.42,clear sky,20.8667,-101.5167,
37,Manaure,CO,85.69,overcast clouds,11.7751,-72.4445,
38,Hilo,US,89.28,overcast clouds,19.7297,-155.0900,
44,Butaritari,KI,81.50,light rain,3.0707,172.7902,
47,Avarua,CK,82.45,scattered clouds,-21.2078,-159.7750,
49,Hithadhoo,MV,83.61,few clouds,-0.6000,73.0833,
54,Taoudenni,ML,89.76,clear sky,22.6783,-3.9836,

In [8]:
# 6a. Set parameters to search for hotels with 5000 meters.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

# 6b. Iterate through the hotel DataFrame.
for index,row in hotel_df.iterrows():
    # 6c. Get latitude and longitude from DataFrame
    lat = row["Lat"]
    lng = row["Lng"]
    params["location"] = f"{lat},{lng}"
    # 6d. Set up the base URL for the Google Places API to get JSON data.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
     # 6e. Make request and retrieve the JSON data from the search. 
    hotels = requests.get(base_url,params = params).json()
    # 6f. Get the first hotel from the results and store the name, if a hotel isn't found skip the city.
    try:
        hotel_df.loc[index,"Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

In [9]:
hotel_df.head(20)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
3,Rikitea,PF,77.29,light rain,-23.1203,-134.9692,People ThankYou
9,Georgetown,MY,84.13,few clouds,5.4112,100.3354,Cititel Penang
28,Jensen Beach,US,85.06,scattered clouds,27.2545,-80.2298,Courtyard by Marriott Hutchinson Island Oceans...
29,Romita,MX,89.42,clear sky,20.8667,-101.5167,HOTEL RESTER
37,Manaure,CO,85.69,overcast clouds,11.7751,-72.4445,Hotel Palaaima
38,Hilo,US,89.28,overcast clouds,19.7297,-155.0900,Hilo Hawaiian Hotel
44,Butaritari,KI,81.50,light rain,3.0707,172.7902,Isles Sunset Lodge
47,Avarua,CK,82.45,scattered clouds,-21.2078,-159.7750,Paradise Inn
49,Hithadhoo,MV,83.61,few clouds,-0.6000,73.0833,Scoop Guest House
54,Taoudenni,ML,89.76,clear sky,22.6783,-3.9836,
56,Boueni,YT,80.58,scattered clouds,-12.9025,45.0761,The feet in water
58,Port Hueneme,US,81.46,clear sky,34.1478,-119.1951,Hampton Inn Channel Islands Harbor
59,Cockburn Town,TC,79.32,broken clouds,21.4612,-71.1419,Osprey Beach Hotel
61,Atuona,PF,78.42,few clouds,-9.8000,-139.0333,Villa Enata
65,Kyabe,TD,88.03,overcast clouds,9.4515,18.9449,
66,Grand-Santi,GF,77.34,moderate rain,4.2500,-54.3833,Hotel La Villa Couacou
67,Vaini,TO,75.36,broken clouds,-21.2000,-175.2000,Keleti Beach Resort
77,Alofi,NU,76.89,broken clouds,-19.0595,-169.9187,Taloa Heights
78,Santa Cruz,BO,81.86,clear sky,-17.8000,-63.1667,Aviador Hotel Boutique
83,Kapaa,US,80.58,overcast clouds,22.0752,-159.3190,Sheraton Kauai Coconut Beach Resort

In [10]:
# 7. Drop the rows where there is no Hotel Name.
# hotel_df = hotel_df.dropna(subset=['Hotel Name'])
# hotel_df.head(30)
hotel_df.replace('',np.nan, inplace=True)
hotel_df.dropna().head(30)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
3,Rikitea,PF,77.29,light rain,-23.1203,-134.9692,People ThankYou
9,Georgetown,MY,84.13,few clouds,5.4112,100.3354,Cititel Penang
28,Jensen Beach,US,85.06,scattered clouds,27.2545,-80.2298,Courtyard by Marriott Hutchinson Island Oceans...
29,Romita,MX,89.42,clear sky,20.8667,-101.5167,HOTEL RESTER
37,Manaure,CO,85.69,overcast clouds,11.7751,-72.4445,Hotel Palaaima
38,Hilo,US,89.28,overcast clouds,19.7297,-155.0900,Hilo Hawaiian Hotel
44,Butaritari,KI,81.50,light rain,3.0707,172.7902,Isles Sunset Lodge
47,Avarua,CK,82.45,scattered clouds,-21.2078,-159.7750,Paradise Inn
49,Hithadhoo,MV,83.61,few clouds,-0.6000,73.0833,Scoop Guest House
56,Boueni,YT,80.58,scattered clouds,-12.9025,45.0761,The feet in water
58,Port Hueneme,US,81.46,clear sky,34.1478,-119.1951,Hampton Inn Channel Islands Harbor
59,Cockburn Town,TC,79.32,broken clouds,21.4612,-71.1419,Osprey Beach Hotel
61,Atuona,PF,78.42,few clouds,-9.8000,-139.0333,Villa Enata
66,Grand-Santi,GF,77.34,moderate rain,4.2500,-54.3833,Hotel La Villa Couacou
67,Vaini,TO,75.36,broken clouds,-21.2000,-175.2000,Keleti Beach Resort
77,Alofi,NU,76.89,broken clouds,-19.0595,-169.9187,Taloa Heights
78,Santa Cruz,BO,81.86,clear sky,-17.8000,-63.1667,Aviador Hotel Boutique
83,Kapaa,US,80.58,overcast clouds,22.0752,-159.3190,Sheraton Kauai Coconut Beach Resort
84,Victoria,HK,76.32,overcast clouds,22.2855,114.1577,Mini Hotel Central
87,Bambous Virieux,MU,77.22,light rain,-20.3428,57.7575,Casa Tia Villa
88,Buala,SB,81.70,light rain,-8.1450,159.5921,Maringe Lagoon Lodge
93,Nha Trang,VN,77.00,overcast clouds,12.2500,109.1833,Hanoi Golden Hotel
94,Kirakira,SB,81.90,broken clouds,-10.4544,161.9205,SanBiz Lodge
99,Carutapera,BR,76.59,overcast clouds,-1.1950,-46.0200,Lidera
102,Puerto Ayora,EC,78.76,scattered clouds,-0.7393,-90.3518,Finch Bay Galapagos Hotel
104,Dingle,PH,77.81,few clouds,10.9995,122.6711,SEGAYA PROPERTY
105,Enid,US,85.01,clear sky,36.3956,-97.8784,Ramada by Wyndham Enid
106,Itarema,BR,78.94,overcast clouds,-2.9248,-39.9167,"Sea Lounge! Bar, Club & Restaurant"
113,Bac Lieu,VN,82.18,overcast clouds,9.2850,105.7244,Khách sạn Sài Gòn Bạc Liêu
114,Yarada,IN,80.92,haze,17.6500,83.2667,Yarada Jungle Beach Resorts

In [11]:
# 8a. Create the output File (CSV)
output_data_file = "WeatherPy_vacation.csv"
# 8b. Export the City_Data into a csv
hotel_df.to_csv(output_data_file, index_label="City_ID")

In [15]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Weather</dt><dd>{Current Description} and {Max Temp} °F</dd>
</dl>
"""
# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame. 
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,
             dissipating=False, max_intensity=300, point_radius=4)
# 11a. Add a marker layer for each city to the map.
marker_layer = gmaps.marker_layer(locations,info_box_content=hotel_info)
# Add a heatmap of temperature for the vacation spots and marker for each city.
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)
# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))